const mongoose = require('mongoose');

const itemSchema = new mongoose.Schema({
  rawData: {
    date: [Date],
    dq1aBuy: [Number],
    dq1aBuyVolume: [Number],
    dq1aBuy: [Number],
    dq1aBuyVolume: [Number],
    jitaBuy: [Number],
    jitaBuyVolume: [Number],
    jitaBuy: [Number],
    jitaBuyVolume: [Number],
    amarrBuy: [Number],
    amarrBuyVolume: [Number],
    amarrBuy: [Number],
    amarrBuyVolume: [Number],
    dq1aSell: [Number],
    dq1aSellVolume: [Number],
    dq1aSell: [Number],
    dq1aSellVolume: [Number],
    jitaSell: [Number],
    jitaSellVolume: [Number],
    jitaSell: [Number],
    jitaSellVolume: [Number],
    amarrSell: [Number],
    amarrSellVolume: [Number],
    amarrSell: [Number],
    amarrSellVolume: [Number],
  },
  aggregates: {
    sampleSize: Number,
    mean: {
      dq1aBuy: Number,
      dq1aBuyVolume: Number,
      dq1aBuy: Number,
      dq1aBuyVolume: Number,
      jitaBuy: Number,
      jitaBuyVolume: Number,
      jitaBuy: Number,
      jitaBuyVolume: Number,
      amarrBuy: Number,
      amarrBuyVolume: Number,
      amarrBuy: Number,
      amarrBuyVolume: Number,
      dq1aSellVolume: Number,
      dq1aSell: Number,
      dq1aSell: Number,
      dq1aSellVolume: Number,
      jitaSell: Number,
      jitaSellVolume: Number,
      jitaSell: Number,
      jitaSellVolume: Number,
      amarrSell: Number,
      amarrSellVolume: Number,
      amarrSell: Number,
      amarrSellVolume: Number,
    },
    std: {
      dq1aBuy: Number,
      dq1aBuyVolume: Number,
      dq1aBuy: Number,
      dq1aBuyVolume: Number,
      jitaBuy: Number,
      jitaBuyVolume: Number,
      jitaBuy: Number,
      jitaBuyVolume: Number,
      amarrBuy: Number,
      amarrBuyVolume: Number,
      amarrBuy: Number,
      amarrBuyVolume: Number,
      dq1aSell: Number,
      dq1aSellVolume: Number,
      dq1aSell: Number,
      dq1aSellVolume: Number,
      jitaSell: Number,
      jitaSellVolume: Number,
      jitaSell: Number,
      jitaSellVolume: Number,
      amarrSell: Number,
      amarrSellVolume: Number,
      amarrSell: Number,
      amarrSellVolume: Number,
    },
    ma5: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    ma10: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    ma20: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
  },
  itemName: { type: String, unique: true },
  volume: Number,
  typeID: { type: Number, unique: true },
  groupID: Number,
  iconID: Number,
  groupName: String,
  marketGroupID: Number,
  keywords: { primary: [String], secondary: [String], tertiary: [String] },
});

const Item = mongoose.model('PriceData', itemSchema);

module.exports = Item;
