const mongoose = require('mongoose');

const itemSchema = new mongoose.Schema({
  rawData: {
    date: [Date],
    dq1aBuy: [Number],
    dq1aBuyVolume: [Number],
    dq1aBuy: [Number],
    dq1aBuyVolume: [Number],
    jitaBuy: [Number],
    jitaBuyVolume: [Number],
    jitaBuy: [Number],
    jitaBuyVolume: [Number],
    amarrBuy: [Number],
    amarrBuyVolume: [Number],
    amarrBuy: [Number],
    amarrBuyVolume: [Number],
    dq1aSell: [Number],
    dq1aSellVolume: [Number],
    dq1aSell: [Number],
    dq1aSellVolume: [Number],
    jitaSell: [Number],
    jitaSellVolume: [Number],
    jitaSell: [Number],
    jitaSellVolume: [Number],
    amarrSell: [Number],
    amarrSellVolume: [Number],
    amarrSell: [Number],
    amarrSellVolume: [Number],
  },
  aggregates: {
    sampleSize: Number,
    importProfits: {
      perUnit: {
        fromJita: {
          current: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          mean: {
            buyToBuy: Number,
            buyToSell: Number,
            sellToBuy: Number,
            sellToSell: Number,
          },
          ma5: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma10: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma20: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
        },

        fromAmarr: {
          current: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          mean: {
            buyToBuy: Number,
            buyToSell: Number,
            sellToBuy: Number,
            sellToSell: Number,
          },
          ma5: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma10: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma20: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
        },
        fromJitaToAmarr: {
          current: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          mean: {
            buyToBuy: Number,
            buyToSell: Number,
            sellToBuy: Number,
            sellToSell: Number,
          },
          ma5: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma10: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma20: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
        },
      },
      perM3: {
        fromJita: {
          current: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          mean: {
            buyToBuy: Number,
            buyToSell: Number,
            sellToBuy: Number,
            sellToSell: Number,
          },
          ma5: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma10: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma20: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
        },
        fromAmarr: {
          current: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          mean: {
            buyToBuy: Number,
            buyToSell: Number,
            sellToBuy: Number,
            sellToSell: Number,
          },
          ma5: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma10: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma20: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
        },
        fromJitaToAmarr: {
          current: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          mean: {
            buyToBuy: Number,
            buyToSell: Number,
            sellToBuy: Number,
            sellToSell: Number,
          },
          ma5: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma10: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
          ma20: {
            buyToBuy: [Number],
            buyToSell: [Number],
            sellToBuy: [Number],
            sellToSell: [Number],
          },
        },
      },
    },
    mean: {
      dq1aBuy: Number,
      dq1aBuyVolume: Number,
      dq1aBuy: Number,
      dq1aBuyVolume: Number,
      jitaBuy: Number,
      jitaBuyVolume: Number,
      jitaBuy: Number,
      jitaBuyVolume: Number,
      amarrBuy: Number,
      amarrBuyVolume: Number,
      amarrBuy: Number,
      amarrBuyVolume: Number,
      dq1aSellVolume: Number,
      dq1aSell: Number,
      dq1aSell: Number,
      dq1aSellVolume: Number,
      jitaSell: Number,
      jitaSellVolume: Number,
      jitaSell: Number,
      jitaSellVolume: Number,
      amarrSell: Number,
      amarrSellVolume: Number,
      amarrSell: Number,
      amarrSellVolume: Number,
    },
    std: {
      dq1aBuy: Number,
      dq1aBuyVolume: Number,
      dq1aBuy: Number,
      dq1aBuyVolume: Number,
      jitaBuy: Number,
      jitaBuyVolume: Number,
      jitaBuy: Number,
      jitaBuyVolume: Number,
      amarrBuy: Number,
      amarrBuyVolume: Number,
      amarrBuy: Number,
      amarrBuyVolume: Number,
      dq1aSell: Number,
      dq1aSellVolume: Number,
      dq1aSell: Number,
      dq1aSellVolume: Number,
      jitaSell: Number,
      jitaSellVolume: Number,
      jitaSell: Number,
      jitaSellVolume: Number,
      amarrSell: Number,
      amarrSellVolume: Number,
      amarrSell: Number,
      amarrSellVolume: Number,
    },
    min5: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    min10: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    min20: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    max5: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    max10: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    max20: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    ma5: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    ma10: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
    ma20: {
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      dq1aBuy: [Number],
      dq1aBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      jitaBuy: [Number],
      jitaBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      amarrBuy: [Number],
      amarrBuyVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      dq1aSell: [Number],
      dq1aSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      jitaSell: [Number],
      jitaSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
      amarrSell: [Number],
      amarrSellVolume: [Number],
    },
  },
  itemName: { type: String, unique: true },
  volume: Number,
  typeID: { type: Number, unique: true },
  groupID: Number,
  iconID: Number,
  groupName: String,
  marketGroupID: Number,
  keywords: { primary: [String], secondary: [String], tertiary: [String] },
});

const Item = mongoose.model('PriceData', itemSchema);

module.exports = Item;
